"""initial

Revision ID: 08ecfdaddee2
Revises: 
Create Date: 2023-12-20 22:49:04.724222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ecfdaddee2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products')
    op.drop_table('Shipments')
    op.drop_table('Enterprise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Enterprise',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Number_Of_Workers', sa.INTEGER(), nullable=False),
    sa.Column('Name_Of_Enterprise', sa.VARCHAR(length=42), nullable=False),
    sa.Column('Activity_Type', sa.VARCHAR(length=42), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Shipments',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Date_Of_Shipment', sa.DATETIME(), nullable=False),
    sa.Column('Volume_Of_Shipment', sa.FLOAT(), nullable=False),
    sa.Column('Sale_Price', sa.FLOAT(), nullable=False),
    sa.Column('Enterprise_Id', sa.INTEGER(), nullable=False),
    sa.Column('Products_Id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['Enterprise_Id'], ['Enterprise.Id'], ),
    sa.ForeignKeyConstraint(['Products_Id'], ['Products.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Products',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Full_Name', sa.VARCHAR(length=42), nullable=False),
    sa.Column('Purchase_Price', sa.FLOAT(), nullable=False),
    sa.Column('Expiration_Date', sa.DATETIME(), nullable=False),
    sa.Column('Unit_Of_Measurement', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###
