"""add column

Revision ID: 24c4cfa9f718
Revises: 1b700f8a9ff8
Create Date: 2023-12-24 12:08:53.398121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, JSONB


# revision identifiers, used by Alembic.
revision: str = '24c4cfa9f718'
down_revision: Union[str, None] = '1b700f8a9ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('json_field', JSON, nullable=True))
    op.execute("UPDATE Products SET json_field = '{}'")  # Populate the JSON field with initial data
    op.create_index('ix_json_field_gin', 'Products', ['json_field'], postgresql_using='gin',
                    postgresql_ops={"json_field": "jsonb_path_ops"})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_json_field_gin', 'Products')
    op.drop_column('Products', 'json_field')
    # ### end Alembic commands ###
