"""json-field

Revision ID: 793491a7254b
Revises: 24c4cfa9f718
Create Date: 2023-12-19 15:43:30.140830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, JSONB

# revision identifiers, used by Alembic.
revision: str = '793491a7254b'
down_revision: Union[str, None] = '24c4cfa9f718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_Products_Full_Name', 'Products', ['Full_name'], postgresql_using='gin')
    op.create_index('idx_Products_Purchase_Price', 'Products', ['Purchase_Price'], postgresql_using='gin')

    op.create_index('idx_Enterprise_Number_Of_Workers', 'Enterprise', ['Number_Of_Workers'], postgresql_using='gin')
    op.create_index('idx_Enterprise_Name_Of_Enterprise', 'Enterprise', ['Name_Of_Enterprise'], postgresql_using='gin')

    op.create_index('idx_Shipments_Volume_Of_Shipment', 'Shipments', ['Volume_Of_Shipment'], postgresql_using='gin')
    op.create_index('idx_Shipments_Sale_Price', 'Shipments', ['Sale_Price'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_Products_Full_Name', table_name='Products')
    op.drop_index('idx_Products_Purchase_Price', table_name='Products')

    op.drop_index('idx_Enterprise_Number_Of_Workers', table_name='Enterprise')
    op.drop_index('idx_Enterprise_Name_Of_Enterprise', table_name='Enterprise')

    op.drop_index('idx_Shipments_Volume_Of_Shipment', table_name='Shipments')
    op.drop_index('idx_Shipments_Sale_Price', table_name='Shipments')
